### ISSUE TITLE
Mention in README that chipmunk can't be unbundled

### ISSUE THREAD

**Issue by akien-mga** [cxong/FallingTime#11]
As any serious (and annoying for upstream developers) packager would do, I've first tried to unbundle chipmunk to build FallingTime against my distro's chipmunk package.

Obviously I broke my teeth on this one, as chipmunk is heavily patched in the source tree so the rest of the codebase won't build with the system chipmunk (as per at least 0a75ad322).
Maybe you could add a mention to this in the _Building_ section of the README?

**Comment by cxong** [comment]
As the commit https://github.com/cxong/FallingTime/commit/0a75ad322c1c59167df0201ddd08d3e14fa9b3dc?diff=unified shows, some of the changes are extra NULL checks, where the library assumed that all bodies contained dynamic shapes etc. I thought about contributing upstream but it seems they're not so active lately, see: https://github.com/slembcke/Chipmunk2D/pull/102

Perhaps I'll try again once they get around to reviewing some of the existing PRs
