### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by akien-mga** [cxong/FallingTime#18]
Hi @cxong, I'm looking again at packaging Falling Time for Mageia (I'm not sure why I didn't go through the last time, probably forgot). Since there are quite a few interesting commits in the current master HEAD, and not much recent activity otherwise, WDYT about making a new 1.1 or 1.0.1 release?

**Comment by cxong** [comment]
https://github.com/cxong/FallingTime/releases/tag/1.0.1

**Comment by akien-mga** [comment]
Awesome, thanks :)
