### ISSUE TITLE
System-wide installation: dehardcode data path

### ISSUE THREAD

**Issue by akien-mga** [cxong/FallingTime#20]
I'd like to package FallingTime for my distro, Mageia. I think I had a look at it already a while ago but somehow never finished my WIP, so here I'm back at it.

It looks like the path to the `./data/` folder is hardcoded in the source. It would be nice to add support for installing the data in a folder like `/usr/share/games/fallingtime`, and thus not next to the binary (that would typically be in `/usr/games` or `/usr/bin`). Two typical solutions to this issue:
- Hardcore various paths in the code, and test each of them to locate the data. Typically it would look first for `./data`, and then (on platform Linux only) for `/usr/share/games/fallingtime` and for `/usr/share/fallingtime` (or the other way around, Debian/Mageia use the former, Fedora uses the latter).
- Use a compilation parameter to define a `DATA_DIR`, and use it in the source code to initialize the constant used as prefix for the data. The fallback can be:

```
#ifndef DATA_DIR
#define DATA_DIR "./data/"
#endif // DATA_DIR
```

A second step for system-wide installation would be to add specific installation instructions in CMakeLists.txt to put the binary and data in the correct places (and maybe .desktop file and icon too). I'd gladly work on it if you can help with the first part described above.

**Comment by cxong** [comment]
Done, as cmake option; give it a go e.g. `cmake -DDATA_DIR=/path/to/dir/` - trailing slash required
