### ISSUE TITLE
High scores loading shows an error when there is no saved high scores yet

### ISSUE THREAD

**Issue by akien-mga** [cxong/FallingTime#24]
When running the game on Mageia 7 x86_64, I get the following error in the terminal:
```
Error: cannot open config file /home/akien/.config/falling_time_high_scores.conf
```
And the file indeed doesn't exist, while `/home/akien/.config` is writable:
```
drwx------ 132 akien akien    12288 Nov  1 13:06  .config/
```
(Running the game as `akien` of course.)

**Comment by akien-mga** [comment]
It only happens as long as there is no high score, once the file exists then it no longer fails. So it's mostly a false positive from https://github.com/cxong/FallingTime/blob/master/high_score.c#L52-L57 where the fail condition is the expected behaviour as long as no high scores exist.

**Comment by cxong** [comment]
9cc480b
